default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight or App Store"
  lane :release do
    setup_ci

    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"],
      in_house: false
    )

    # Otomatik Kod İmzalama (Automatic Code Signing)
    # Match yerine Xcode'un otomatik imzalama özelliğini API Key ile kullanıyoruz.
    build_app(
      workspace: "App.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates"
    )

    upload_to_app_store(skip_screenshots: true, skip_metadata: true)
  end
end
